MergeTest
power-rangers-ireland/Calendar-UI pull request #6
Opened 2021-08-03 15:46 UTC by S00185883

2021-08-03 15:55 UTC, S00189591 approved these changes
Looks good, just consider cleanup some of the code

2021-08-03 15:55 UTC, S00189591 commented on src/components/header/header.js
> +    </header>
consider cleanup divs?
```suggestion
      
        <div className='navbar__title navbar__item'><img src={logo} /></div>
        <div className='navbar__item'> </div>
        <div className='navbar__item'> 
        <Popup modal trigger={<button className="info_button"><FaInfoCircle /> Office Re-Entery Requirements</button>}>
        {close => <Content close={close} />}
      </Popup>
      </div>
    </header>
```

2021-08-03 15:55 UTC, S00189591 commented on src/components/popup/popup.css
> +  }
Again, consider ensuring code is neat and inline

2021-08-03 15:57 UTC, Clancinio commented on src/components/popup/popup.css
> +  }
We should all make sure we are using the prettier extension in VS code so our formatting will be in sync.

2021-08-03 16:10 UTC, Clancinio commented on src/components/popup/entryPopUp.js
> +export default ({ close }) => (
function EntryPopUp({ close }) {
  return (
    <div className="modal">
       ............code
    </div>
  );
}

2021-08-03 16:10 UTC, Clancinio requested changes
Components should be PascalCase :)

2021-08-04 07:29 UTC, S00185883 commented on src/components/popup/entryPopUp.js
> +export default ({ close }) => (
it took this long enough to work i cant risk changing it when i know it works like this

2021-08-04 07:47 UTC, Clancinio commented on src/components/popup/entryPopUp.js
> +export default ({ close }) => (
Shouldn't effect functionality though. It's just for consistency/convention.

2021-08-04 09:36 UTC, S00189802 approved these changes

2021-08-04 09:38 UTC, merged